; Generated by Zirco Bootstrap Compiler

define i32 @add(i32 %x.param, i32 %y.param) {
  %t0 = load i32, i32* %x
  %t1 = load i32, i32* %y
  %t2 = add i32 %t0, %t1
  ret i32 %t2
}

define i32 @factorial(i32 %n.param) {
  %t3 = load i32, i32* %n
  %t4 = add i32 0, 2
  %t5 = icmp slt i32 %t3, %t4
  br i1 %t5, label %L0, label %L1
L0:
  %t6 = add i32 0, 1
  ret i32 %t6
  br label %L1
L1:
  %t7 = load i32, i32* %n
  %t8 = call i32 @factorial()
