; Generated by Zirco Bootstrap Compiler

define i32 @simple() {
  %t0 = add i32 0, 42
  ret i32 %t0
}

define i32 @main() {
  %x = alloca i32
  %t1 = add i32 0, 5
  store i32 %t1, i32* %x
  %y = alloca i32
  %t2 = add i32 0, 10
  store i32 %t2, i32* %y
  %t3 = add i32 0, 0
  ret i32 %t3
}

