//! Build information for the Zirco compiler.
//!
//! This module is responsible for generating and providing access to the
//! compiler's version string as generated by build.rs.

/// The version string is generated at compile time and includes information
/// such as the package name, version, git commit and branch, build type,
/// operating system, and architecture.
pub const VERSION_STRING: &str = include_str!(concat!(env!("OUT_DIR"), "/version"));
