[package]
name = "zrc_codegen"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zrc_typeck = { path = "../zrc_typeck" }
zrc_utils = { path = "../zrc_utils" }
tracing = { version = "0.1.44", features = ["release_max_level_warn"] }

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
features = ["llvm23-1", "llvm23-1-prefer-static"]

[dev-dependencies]
indoc = "2.0.5"
insta = { version = "1.36.1", features = ["yaml"] }
zrc_parser = { path = "../zrc_parser" }
