[package]
name = "zrc_hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zrc_parser = { version = "0.1.0", path = "../zrc_parser" }
