[package]
name = "zrc_jit"
version = "0.2.0"
edition = "2024"

[dependencies]
zrc_typeck = { path = "../../compiler/zrc_typeck" }
zrc_utils = { path = "../../compiler/zrc_utils" }
zrc_codegen = { path = "../../compiler/zrc_codegen" }
tracing = { version = "0.1.44", features = ["release_max_level_warn"] }

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
features = ["llvm23-1", "llvm23-1-prefer-static"]
