[package]
name = "zrc_jit"
version = "0.2.0"
edition = "2024"

[dependencies]
zrc_typeck = { path = "../../compiler/zrc_typeck" }
zrc_utils = { path = "../../compiler/zrc_utils" }
zrc_codegen = { path = "../../compiler/zrc_codegen" }
inkwell = { version = "0.10.0", features = [
    "llvm22-1",
    "llvm22-1-prefer-static",
] }
tracing = { version = "0.1.44", features = ["release_max_level_warn"] }
