name: "fmt-fix"

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    fmt-fix:
        runs-on: ubuntu-latest
        # Only run on PRs from the same repository (not forks) for security
        if: github.event.pull_request.head.repo.full_name == github.repository
        
        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt
            
            - name: Run rustfmt
              run: cargo +nightly fmt
            
            - name: Check for changes
              id: verify_diff
              run: |
                  git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
            
            - name: Commit and push if changed
              if: steps.verify_diff.outputs.changed == 'true'
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Apply rustfmt formatting"
                  git push
